// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbfbzycgooafbedfslwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiZmJ6eWNnb29hZmJlZGZzbHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTA2OTYsImV4cCI6MjA3Mzk2NjY5Nn0.ZOAq4KCfeNHvWP0ymXJdBkaH8-F9Rgj1DaE09fo1N54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});